[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.3"
macroquad = "0.4.4"
ndarray = "0.15.6"
num_cpus = "1.16.0"
rand = "0.8.5"
threadpool = "1.8.1"
